// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3BuTwmAiHWck03lnIIbRuoDJNKzlxTkA',
    appId: '1:73814158533:web:e72c0338d737f311a414ac',
    messagingSenderId: '73814158533',
    projectId: 'gausampada-48ab2',
    authDomain: 'gausampada-48ab2.firebaseapp.com',
    storageBucket: 'gausampada-48ab2.firebasestorage.app',
    measurementId: 'G-GLD1CDMPX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_6990eEI2EUzKYAwSkxRbLPx1XiLdJBQ',
    appId: '1:73814158533:android:4bf2e45054b1c250a414ac',
    messagingSenderId: '73814158533',
    projectId: 'gausampada-48ab2',
    storageBucket: 'gausampada-48ab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbrY53tQLzhlrHr4GbXM1gYYNSPMf_yQ',
    appId: '1:73814158533:ios:07fe7778fcdfdcdba414ac',
    messagingSenderId: '73814158533',
    projectId: 'gausampada-48ab2',
    storageBucket: 'gausampada-48ab2.firebasestorage.app',
    iosBundleId: 'com.example.gausampada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbrY53tQLzhlrHr4GbXM1gYYNSPMf_yQ',
    appId: '1:73814158533:ios:07fe7778fcdfdcdba414ac',
    messagingSenderId: '73814158533',
    projectId: 'gausampada-48ab2',
    storageBucket: 'gausampada-48ab2.firebasestorage.app',
    iosBundleId: 'com.example.gausampada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3BuTwmAiHWck03lnIIbRuoDJNKzlxTkA',
    appId: '1:73814158533:web:0f82da1f32f0ef4fa414ac',
    messagingSenderId: '73814158533',
    projectId: 'gausampada-48ab2',
    authDomain: 'gausampada-48ab2.firebaseapp.com',
    storageBucket: 'gausampada-48ab2.firebasestorage.app',
    measurementId: 'G-Q2Y5GTQ3E7',
  );

}